name: Deploy Astro to Seohost

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # lub Twoja wersja pnpm

      - name: Build Astro
        run: |
          pnpm install
          pnpm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ 
          server-dir: /public_html/
          exclude: |
            **/blog/**
            **/wp-admin/**
            **/wp-content/**
            **/wp-includes/**
            wp-config.php
            .htaccess
          protocol: ftp
          port: 21
          stateful: true
